name: Build Umi Project

on:
  push:
    branches:
      - main # 或者 master，按你的分支来改
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 或你项目用的版本

      - name: Install dependencies
        run: npm install # 或者 yarn / pnpm install

      - name: Build the project
        run: npm run build # 默认 umi 项目是这个命令
